use_frameworks!

platform :ios, '9.0'

target 'MNSwiftPods_Example' do
  pod 'MNSwiftPods', :path => '../'

  target 'MNSwiftPods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
